# Generated by Django 4.0 on 2023-01-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField()),
                ('due_back', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
    ]
