# Generated by Django 4.0 on 2023-02-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_borrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
