# Generated by Django 4.0 on 2023-02-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='',
        ),
    ]
