# Generated by Django 4.0 on 2023-02-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_bookinstance_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
    ]
