# Generated by Django 4.0 on 2023-02-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
